# Generated by Django 3.2.8 on 2021-10-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='popularity',
        ),
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
