# Generated by Django 3.2.8 on 2021-10-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211014_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='allow_to_comment',
            new_name='allowed_to_comment',
        ),
    ]
