# Generated by Django 3.2.8 on 2021-10-18 18:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_allow_to_comment_customer_allowed_to_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.color')),
            ],
        ),
    ]
