# Generated by Django 3.2.8 on 2021-11-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211102_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
