# Generated by Django 3.2.8 on 2021-11-22 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('content', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
